"""Add safo oso columns

Revision ID: abc9529c2b4e
Revises: 1a31ce608336
Create Date: 2024-11-07 11:14:45.205931

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'abc9529c2b4e'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('ora_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('user', sa.Column('oso_kod', sqlmodel.sql.sqltypes.AutoString(length=6), nullable=True))
    op.add_column('user', sa.Column('fir_kod', sqlmodel.sql.sqltypes.AutoString(length=6), nullable=True))
    op.create_index(op.f('ix_user_ora_id'), 'user', ['ora_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_ora_id'), table_name='user')
    op.drop_column('user', 'fir_kod')
    op.drop_column('user', 'oso_kod')
    op.drop_column('user', 'ora_id')
    # ### end Alembic commands ###
